### ISSUE TITLE
PWA

### ISSUE THREAD

**Issue by RabigaSB** [RabigaSB/LetsPlaySoccer#101]
**Что нужно сделать?**
Запустить приложение с помощью PWA.

**Зачем это нужно?**
Чтобы юзер мог пользоваться приложением не со страницы в браузере, а как с мобильного приложения. 

**Как это сделать**
Создать manifest.json если его нет.
Создать serviceWorker.js если его нет.
Подключить логотип в manifest.json.

**Критерий приемки**
Зайти на страницу сайта и на андроиде вспылает окно добавить на домашний экран.

**Планируемое время работы:**
16 часов

**Comment by sound0terror** [comment]
**01.10.19** Приступил в **17.00**
**01.10.19** Приостановил в **19.00**
**02.10.19** Возобновил в **18.00**
**02.10.19** Приостановил в **22.00**
**03.10.19** Возобновил в **13.00**
**03.10.19** Закончил в **16.00**
