### ISSUE TITLE
Создать получение и вывод полей на фронте

### ISSUE THREAD

**Issue by kasienov2001** [RabigaSB/LetsPlaySoccer#35]
**Что нужно сделать?**
Сделать такой интерфейс и получение полей
https://prnt.sc/om1xhn

**Как это сделать?**
Вспомнить получение продуктов с занятия:
https://git.attractor-school.com/flintstoneChurchill/shop-frontend

**Критерии приёмки:**
-Получение данных с сервера
-Вывод на странице
-Создание рута для поля

**Планируемое время работы:**
10ч

**Comment by RabigaSB** [comment]
**09.08.2019** started at **21:53**

**Comment by RabigaSB** [comment]
**09.08.2019** paused at **22:15**

**Comment by RabigaSB** [comment]
**10.08.2019** resumed at **2:00**

**Comment by RabigaSB** [comment]
**10.08.2019** paused at **2:30**

**Comment by RabigaSB** [comment]
**10.08.2019** started at **16:40**

**Comment by RabigaSB** [comment]
10.08.2019 paused at 19:00

**Comment by RabigaSB** [comment]
14.08.2019 started at 15:00
14.08.2019 paused at 18:30
16.08.2019 started at 11:23

**Comment by RabigaSB** [comment]
16.08.2019 paused at 13:46
16.08.2019 started at 15:18

**Comment by RabigaSB** [comment]
16.08.2019 paused at 14:03

**Comment by RabigaSB** [comment]
**18.08.2019** started at **13:00**
**18.08.2019** paused at **16:30**
