### ISSUE TITLE
Сделать страницу создания матча на фронте

### ISSUE THREAD

**Issue by kasienov2001** [RabigaSB/LetsPlaySoccer#36]
**Что нужно сделать?**
Создать интерфейс для создания матча ПОКА БЕЗ КАРТЫ
https://prnt.sc/om2j7t

**Критерии приёмки:**
-Создание рута и контейнера для создания поля
-Создание dropdown'a для даты матча
-Создание скролла для времени

**Планируемое время работы:**
5ч

**Comment by Rikling** [comment]
приступил в 5:50

**Comment by Rikling** [comment]
приостановлено в 9:20

**Comment by Rikling** [comment]
продолжил в 5:30

**Comment by Rikling** [comment]
приостановлено в 8:10

**Comment by RabigaSB** [comment]
spent: 2hours
