### ISSUE TITLE
Показать структуру данных приходящих с бэка фронтэндщику

### ISSUE THREAD

**Issue by kasienov2001** [RabigaSB/LetsPlaySoccer#37]
**Что нужно сделать?**
Показать примерную структуру данных приходящих на frontend при создании матча и для получения полей 

**Зачем это нужно?**
Чтобы фронтенд можно было написать параллельно с бэком и не ждать его создания

**Критерии приёмки:** 
-Орально или ввиде json файла показать структуру приходящих json данных

**Comment by sound0terror** [comment]
Обговорили с командой и закрыли тикет
