### ISSUE TITLE
Создать валидацию для юзера

### ISSUE THREAD

**Issue by kasienov2001** [RabigaSB/LetsPlaySoccer#38]
**Что нужно сделать?**
-Поставить ограничение кол-ва символов в пароле и displayName
-Создать словарь из допустимых символов для пароля 

**Как это сделать?**
Использовать символы отсюда
http://support.ricoh.com/bb_v1oi/pub_e/oi_view/0001050/0001050883/view/security/int/0010.htm
либо найти уже готовые словари 

**Критерии приёмки:** 
-нельзя создать пароль и displayName c символами превышающими ограничение
-создан словарь из допустимых символов

**Планируемое время работы:**

**Comment by sound0terror** [comment]
**29.08.2019** Приступил в **15.00**

**Comment by sound0terror** [comment]
**30.08.2019** Закончил в **12.50**
