### ISSUE TITLE
Сделать пагинацию при получении полей

### ISSUE THREAD

**Issue by kasienov2001** [RabigaSB/LetsPlaySoccer#41]
**Что нужно сделать?**
Создать пагинацию которая будет выводить только часть полей а не все сразу

**Как это сделать?**
-реализовать это на бэке и на фронте
https://medium.com/@mmccabe/pagination-with-thousands-of-database-records-using-node-sequelize-and-react-2af35cff4b4
-можно использовать инструкцию по ссылке для фронта
https://www.npmjs.com/package/react-scrollable-pagination
-эту для бэка
https://www.npmjs.com/package/sequelize-paginate

**Зачем это нужно?**
Чтобы не перенагружать фронт и сервер

**Критерии приёмки:**
-на бэке изначально присылается только определенное кол-во полей(например, 15)
-фронт принимает только определенное кол-во полей(например, 15)

**Планируемое время работы:**
1 час

**Comment by sound0terror** [comment]
**03.09.2019** Приступил в **13.00**
**03.09.2019** Закончил в **13.40**
