### ISSUE TITLE
Создать руты для поля и зависимых сущностей на бэке

### ISSUE THREAD

**Issue by kasienov2001** [RabigaSB/LetsPlaySoccer#42]
**Что нужно сделать?**
Создать рут для поля и если понадобится для дня, времени, формата и image

**Критерии приёмки:**
-У поля есть get, post запросы
-У требуемых для создания поля сущностей(день, время, формат, image) есть post запросы 

**Планируемое время работы:**
10 часа

**Comment by sound0terror** [comment]
Разбили тикет на мелкие части
