### ISSUE TITLE
Создать сущность cover для БД 

### ISSUE THREAD

**Issue by kasienov2001** [RabigaSB/LetsPlaySoccer#47]
**Что нужно сделать?**
Создать модель cover для базы данных

**Как это сделать?**
Создать аттрибут имя и взязать с полем, так же создать роуты post и get

**Зачем это нужно?**
Для того чтобы юзеры могли заполнять типы покрытия поля
**Критерии приёмки:** 

**Планируемое время работы:** 
1 час

**Comment by sound0terror** [comment]
**08.08.2019** Приступил в **19:30**

**Comment by sound0terror** [comment]
**08.08.2019** Закончил в **20:20**
