### ISSUE TITLE
Создать сущность Format для БД

### ISSUE THREAD

**Issue by Rikling** [RabigaSB/LetsPlaySoccer#48]
**Что нужно сделать?**

Создать модель format для базы данных c роутами get и post

**Как это сделать?**

Создать модель format и связать его с полем

**Зачем это нужно?**

Что бы обозначать максимальное количество человек в команде 

**Критерии приёмки:**
Должна быть возможность хранить несколько форматов для 1 поля
  
**Планируемое время работы:**
1 час

**Comment by sound0terror** [comment]
**08.08.2019** Приступил в **19:40**

**Comment by sound0terror** [comment]
**08.08.2019** Закончил в **20:20**
