### ISSUE TITLE
добавить роуты для Type БД

### ISSUE THREAD

**Issue by Rikling** [RabigaSB/LetsPlaySoccer#49]
**Что нужно сделать?**

Добавить роуты get и post для сущности Type 

**Критерии приёмки:**
Должна быть возможность  отправлять и принимать запросы

**Планируемое время работы:**
1 час

**Comment by sound0terror** [comment]
**09.08.2019** Приступил в **19:00**

**Comment by sound0terror** [comment]
**09.08.2019** Закончил в **20:00**
