### ISSUE TITLE
Сверстать страницу Profile 

### ISSUE THREAD

**Issue by Rikling** [RabigaSB/LetsPlaySoccer#51]
**Что нужно сделать?**
Сверстать адаптивную страницу profile

**Как это сделать?**

**Зачем это нужно?**
Для возможности пользователю загрузить аватарку

**Критерии приёмки:**

Должна быть возможность  загрузить аватарку через профиль пользователя

**Планируемое время работы:**
4 часа

**Comment by sound0terror** [comment]
Почему тикет на 4 часа висит уже 17 дней?

**Comment by RabigaSB** [comment]
Потому что нужно сначала закончить с другими страницами, матчи и поле

**Comment by Rikling** [comment]
закончил за 3.5 дня а планировал за 2.5
