### ISSUE TITLE
Сделать возможность добавления картинок для поля

### ISSUE THREAD

**Issue by RabigaSB** [RabigaSB/LetsPlaySoccer#55]
**Что нужно сделать?**
Сделать возможность добавления картинок

**Как это сделать?**
Воспользоваться встроенной библиотекой fs

**Зачем это нужно?**
Чтобы передавать и получать фотографии полей

**Критерии приёмки:**
- Создаются папки с id поле
- А внутри загруженные файлы

**Планируемое время работы:**30 min

**Comment by sound0terror** [comment]
Перенаправил тикет на другого разработчика чтобы разгрузить процесс

**Comment by kasienov2001** [comment]
Приступил в 19:00, Завершил в 20:30
Потрачено времени: 1.5 часа
