### ISSUE TITLE
Создать ключ image для поля

### ISSUE THREAD

**Issue by kasienov2001** [RabigaSB/LetsPlaySoccer#56]
**Что нужно сделать?**
Создать сохранение фотографий поля на бэке 
**Как это сделать?**
Использовать multer, посмотреть в доке как сохранять сразу несколько фотографий и ставить ограницение в размере файла
https://www.npmjs.com/package/multer
https://stackoverflow.com/questions/34697502/how-to-limit-the-file-size-when-uploading-with-multer
https://scotch.io/tutorials/advanced-photo-upload-in-node
**Критерии приёмки:** 
-Можно загружать сразу несколько фото 
-Есть лимит в 1Мб на фото 
-При загрузке на сервер фото сохраниются в папку для каждого поля внутри общей папки поля
-Структура примерно такая: 
https://prnt.sc/oqvyvt
**Планируемое время работы:**

**Comment by sound0terror** [comment]
Решили создавать картинки в папке с айди поля, нет надобности хранить путь в базе
