### ISSUE TITLE
Создать сущность матча на бэке

### ISSUE THREAD

**Issue by sound0terror** [RabigaSB/LetsPlaySoccer#58]
**Что нужно сделать?**

Создать модель Match со всеми входными данными

**Как это сделать?**

Создать файл Match.js и описать каждое поле которое будет содержать эта сущность.

**Зачем это нужно?**

Чтобы хранить все данные о матче в базе данных.

**Критерии приёмки:**

- Продумать все возможные поля для матча
- Провалидировать то что считаете нужным
- Осуществить связи между матчем, полем и юзером

**Планируемое время работы:**

3 дня

**Comment by kasienov2001** [comment]
Начал: 20:00 14.08
Закончил 20:00 16.08
