### ISSUE TITLE
Сделать logout на фронте

### ISSUE THREAD

**Issue by kasienov2001** [RabigaSB/LetsPlaySoccer#62]
**Что нужно сделать?**
Сделать кнопку logout для юзера на фронте активной 

**Как это сделать?**
Посмотреть прошлые раздакти, или можно просто копипастнуть logout с shop-api из прошлых занятий

**Зачем это нужно?**
Чтоб юзер мог разлогинится

**Критерии приёмки:**
-Запрос на бэк работает без ошибок
-Юзер переходит на страницу login после логаута

Планируемое время:**
2ч

**Comment by RabigaSB** [comment]
24.08.2019 started at 18:40
                    finished at 19:10
