### ISSUE TITLE
Пофиксить инпут у создания матча

### ISSUE THREAD

**Issue by kasienov2001** [RabigaSB/LetsPlaySoccer#64]
**Что нужно сделать?**
У инпута количества команд возле цифры показывается слово "часов" его нужно убрать

**Как это сделать?**
убрать или исправить timeword в коде

**Зачем это нужно?**
Чтобы не дизориентировать юзера

**Критерии приёмки:**
-у инпута нет слова "часов"  в плэйсхолдере
- проверить все инпуты

Планируемое время:**
1 час

**Comment by RabigaSB** [comment]
22.08.2019 started at 21:30

**Comment by RabigaSB** [comment]
22.08.2019 paused at 21:45

**Comment by RabigaSB** [comment]
24.08.2019 started at 14:38

**Comment by RabigaSB** [comment]
24.08.2019 finished at 18:35
