### ISSUE TITLE
Сделать фильтр для полей 

### ISSUE THREAD

**Issue by kasienov2001** [RabigaSB/LetsPlaySoccer#65]
**Что нужно сделать?**
Сделать фильтр полей по типу по покрытию и душу

**Как это сделать?**
Посмотреть прошлые занятия по сортировке данных

**Зачем это нужно?**
Чтобы юзер мог выбирать нужные ему поля по критериям 

**Критерии приёмки:**
-Можно производить поиск поля по категориям типа покрытия и душа

**Планируемое время работы:**
5 ч

**Comment by sound0terror** [comment]
**02.09.2019** Приступил в **17.00**
**02.09.2019** Приостановил в **21.00**
**03.09.2019** Закончил в **13.40**
