### ISSUE TITLE
Сделать поиск поля на бэке

### ISSUE THREAD

**Issue by kasienov2001** [RabigaSB/LetsPlaySoccer#67]
**Что нужно сделать?**
Создать новые руты для поиска поля по имени

**Как это сделать?**
Посмотреть в интернете

**Зачем это нужно?**
Чтобы облегчить поиск нужного поля для юзера

**Критерии приёмки:**
-Юзер может найти юзера по названию поля

Планируемое время:**
1 час

**Comment by sound0terror** [comment]
**03.09.2019** Приступил в **13.40**

**Comment by sound0terror** [comment]
**03.09.2019** Закончил в **14.20**
