### ISSUE TITLE
Сделать показатель цены за игрока на фронте

### ISSUE THREAD

**Issue by kasienov2001** [RabigaSB/LetsPlaySoccer#70]
**Что нужно сделать?**
Вычислять цену которую должен заплатить каждый игрок за матч 

**Как это сделать?**
разделить цену на кол-во игроков и вывести это

**Зачем это нужно?**
Чтобы у юзеров была инфа о стоимости матча

**Критерии приёмки:**
-Цена матча правильно расчитывается
-цены корректно выводится

Планируемое время:** 
1ч

**Comment by RabigaSB** [comment]
Сделала когда исправляла инпуты, тикет #64
