### ISSUE TITLE
Cверстать страницу подтверждения номера телефона

### ISSUE THREAD

**Issue by RabigaSB** [RabigaSB/LetsPlaySoccer#72]
**Что нужно сделать?**
- найти библиотеку для функционала, например [react-verification-input](https://www.npmjs.com/package/react-verification-input)
- изменить стили по дизайну
- пока код подтверждения захардкодить

**Как это сделать?**
- Гуглить

**Зачем это нужно?**

Чтобы юзер мог подтвердить свой номер и номер был валидным, чтобы к нему могли дозвониться

**Критерии приёмки:**
- по дизайну совпадало 
- функционал на стороне работает, данные с бэка можно пока захардкодить

**Планируемое время:**
1.5д

**Comment by Rikling** [comment]
закончил работу за 1 день
