### ISSUE TITLE
Создать middleware для авторизации

### ISSUE THREAD

**Issue by RabigaSB** [RabigaSB/LetsPlaySoccer#77]
**Что нужно сделать?**
Cоздать middleware auth, например

```javascript
const User = require('../models/User');

const auth = async (req, res, next) => {
	const token = req.get('Authorization');
	if(!token) return res.status(401).send('No token found');

	const user = await User.findOne({token});
	if (!user) return res.status(401).send('No user found');

	req.user = user;

	next();

};

module.exports = auth;
```

**Как это сделать?**

Гуглить

**Зачем это нужно?**
Чтобы проверять авторизован ли пользователь

**Критерии приёмки:**
- Есть валидный middleware

**Планируемое время:**
30 минут

**Comment by sound0terror** [comment]
**03.09.2019** Приступил в **16.30**

**Comment by sound0terror** [comment]
**03.09.2019** Закончил в **17.00**
