### ISSUE TITLE
cоздать middleware permit

### ISSUE THREAD

**Issue by RabigaSB** [RabigaSB/LetsPlaySoccer#78]
**Что нужно сделать?**
Cоздать middleware permit, например

```javascript
const permit = (...roles) => {
	return (req, res, next) => {

		if(!req.user) {
			return res.status(401).send({message: 'Unauthorized!'});
		}
		if(!roles.includes(req.user.role)) {
			return res.status(403).send({message: 'Unauthorized'});
		}

		next();
	};
};

module.exports = permit;
```

**Как это сделать?**

Гуглить

**Зачем это нужно?**
Чтобы проверять есть ли пользователя права

**Критерии приёмки:**
- Есть валидный middleware

**Планируемое время:**
30 минут

**Comment by sound0terror** [comment]
**03.09.2019** Приступил в **16.30**

**Comment by sound0terror** [comment]
**03.09.2019** Закончил  в **17.00**
