### ISSUE TITLE
Создать отзывы к матчу

### ISSUE THREAD

**Issue by Rikling** [RabigaSB/LetsPlaySoccer#81]
**Что нужно сделать?**
Добавит возможность оставлять комментарии для участников матча

**Как это сделать?**
Можно взять часть кода из домашек

**Зачем это нужно?**
Для определения рейтинга игры 

**Критерии приёмки:**
Возможность оставлять отзыв и коммент к игре

**Планируемое время:**

**Comment by RabigaSB** [comment]
Не успеем закончить, закрываю, чтобы очистить перечень задач, потом можно переоткрыть эту задачку
