### ISSUE TITLE
Синхронизация данных с бэка

### ISSUE THREAD

**Issue by Rikling** [RabigaSB/LetsPlaySoccer#83]
**Что нужно сделать?**
Синхронизировать получаемые данные с бэка

**Как это сделать?**

**Зачем это нужно?**
Для оптимальной работы приложения

**Критерии приёмки:**
Что бы на фронте всё отображалось и работало

**Планируемое время:**
1 час

**Comment by sound0terror** [comment]
**03.09.2019** Приступил в **21.00**
**03.09.2019** Закончил в **22.00**
