### ISSUE TITLE
Сделать пагинацию поля

### ISSUE THREAD

**Issue by Rikling** [RabigaSB/LetsPlaySoccer#87]
**Что нужно сделать?**
Сделать пагинацию полей

**Как это сделать?**

**Зачем это нужно?**
Для ускорения работы приложения 

**Критерии приёмки:**

**Планируемое время работы:**
1 час

**Comment by sound0terror** [comment]
**03.09.2019** Приступил в **21.00**
**03.09.2019** Закончил в **22.00**
