### ISSUE TITLE
Сделать профиль функционально работающим

### ISSUE THREAD

**Issue by RabigaSB** [RabigaSB/LetsPlaySoccer#99]
**Что нужно сделать?**
Сделать фильтр полей по типу по покрытию и душу
![image](https://user-images.githubusercontent.com/43925943/65420648-8817e600-de23-11e9-956f-67b3d7cfc27a.png)

- Активировать ссылку "Профиль"  в меню

![image](https://user-images.githubusercontent.com/43925943/65420406-e4c6d100-de22-11e9-848d-f85e739d245c.png)

- Принимать запросы с бэка, менять данные и сохранять их 

**Зачем это нужно?**
Чтобы юзер мог изменять свои данные, загружать аватарки

**Критерии приёмки:**
- Полноценный рабочий функционал фронта

**Планируемое время работы:**

**Comment by sound0terror** [comment]
**04.10.2019** Приступил в **13.00**
**04.10.2019** Закочнил в **16.00**
